service: serverless-bert-lambda-docker

provider:
  name: aws # provider
  region: us-east-1 # aws region
  memorySize: 3008 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

functions:
  questionanswering:
    image: 334847460589.dkr.ecr.us-east-1.amazonaws.com/bert-lambda@sha256:511d34e1a5fa2d0936a7a3d451898a56bb7b33acbd4cbb7bf3129ba630d32e37 #ecr url
    events:
      - http:
          path: qa # http path
          method: post # http method